routes/web.php
<?php

use App\Http\Controllers\BlogController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
// Route::get('/blog', [BlogController::class, 'index']);
// Route::post('/blog/create', [BlogController::class, 'create']);
// Route::resource('blog', BlogController);
Route::resource('blog', BlogController::class);

app/Models/Blog-old.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = ['id', 'title', 'content'];
    public $blogs = array();


    public static function addBlog($blog)
    {
        array_push($blogs, $blog);
        print($blogs);
        return $blogs;
    }
}

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    public $timestamps = false;

    protected $fillable = ['id', 'title', 'content'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Facade\FlareClient\Http\Response;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    public function index()
    {
        $blogs = Blog::all();
        // dd($blogs);
        return view('blog.index', compact('blogs'));
    }

    public function create()
    {
        return view('blog.create');
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'id' => 'required|string',
            'title' => 'required|string|min:5|max:100',
            'content' => 'required|string|min:5|max:2000',
        ]);

        $blog = Blog::create($validated);
        return redirect('/blog');
    }

    public function show($id)
    {
    }


    public function edit($id)
    {
        $blog = Blog::findOrFail($id);

        return view('blog.edit', compact('blog'));
    }

    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'title' => 'required|string|min:5|max:100',
            'content' => 'required|string|min:5|max:2000',
        ]);

        Blog::whereId($id)->update($validated);

        return redirect('/blog');
    }

    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);
        $blog->delete();

        return redirect('/blog');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/blog/create.blade.php
@extends('layouts.base')

@section('content')
<section>
    <div class="container mx-auto">
        <div class="w-3/5 mx-auto">
            <h1 class="text-lg text-blue-600 uppercase py-4">Create Blog</h1>
            <form method="post" action="{{ route('blog.store') }}" class="flex flex-col space-y-4">
                @csrf
                <input type="number" class="py-3 px-2 border border-blue-500 rounded" placeholder="Blog #" name="id" />
                <input type="text" class="py-3 px-2 border border-blue-500 rounded" placeholder="title" name="title" />
                <input type="text" class="py-3 px-2 border border-blue-500 rounded" placeholder="blog content" name="content" />
                <button type="submit" class="px-2 py-4 bg-blue-600 rounded text-white uppercase">
                    Submit
                </button>
        </div>
        </form>
    </div>
</section>

@endsection

resources/views/blog/edit.blade.php
@extends('layouts.base')

@section('content')
<section>
    <div class="container mx-auto">
        <div class="w-3/5 mx-auto">
            <h1 class="text-lg text-blue-600 uppercase py-4">Edit Blog {{$blog->id}}</h1>
            <form method="post" action="{{ route('blog.update', $blog->id ) }}" class="flex flex-col space-y-4">
                @csrf
                @method('PATCH')
                <input type="number" class="py-3 px-2 border border-blue-500 rounded" placeholder="Blog #" name="id" disabled value="{{$blog->id}}" />
                <input type="text" class="py-3 px-2 border border-blue-500 rounded" placeholder="title" name="title" value="{{$blog->title}}" />
                <input type="text" class="py-3 px-2 border border-blue-500 rounded" placeholder="blog content" name="content" value="{{$blog->content}}" />
                <button type="submit" class="px-2 py-4 bg-blue-600 rounded text-white uppercase">
                    Submit
                </button>
        </div>
        </form>
    </div>
</section>

@endsection

resources/views/blog/index.blade.php
@extends('layouts.base')

@section('styles')
@endsection

@section('content')
<section class="h-screen w-screen p-8 bg-[FEFEFF]">
    <div class="h-32 w-full">
        <a href="{{ route('blog.create')}}" class="px-4 py-4 bg-blue-600 rounded text-white uppercase">Create</a>
    </div>
    <div class="grid grid-cols-3 gap-2">
        @foreach($blogs as $blog)
        <div class="bg-blue-200 flex-1 py-6 px-2 rounded shadow-sm">
            <div class="w-auto h-36 rounded space-y-2">
                <h1 class="text-2xl font-bold">ID: {{$blog->id}}</h1>
                <h2 class="text-xl opacity-90">Title: {{$blog->title}}</h2>
                <p class="text-base">Content: {{$blog->content}}</p>
            </div>
            <div class="h-8 w-full flex justify-between">
                <a href="{{ route('blog.edit', $blog->id)}}" class="text-white text-2xl">Edit</a>
                <form action="{{ route('blog.destroy', $blog->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="text-red-700 text-2xl" type="submit">Delete</button>
                </form>
            </div>
        </div>
        @endforeach
    </div>
</section>
@endsection

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
    <div class="flex-1">
        @yield('content')
    </div>

    @yield('scripts')
</body>

</html>